# Generated by Django 3.2.7 on 2022-03-30 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=26)),
                ('password', models.CharField(max_length=12)),
                ('first_name', models.CharField(max_length=26)),
                ('last_name', models.CharField(max_length=26)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('ADMIN', 'ADMIN'), ('WRITER', 'WRITER'), ('REGISTERED', 'REGISTERED'), ('GUEST', 'GUEST')], max_length=10)),
                ('phone', models.CharField(default='444-444-4444', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
            ],
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='api.account')),
                ('following_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='api.account')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('headline', models.CharField(max_length=100)),
                ('rating', models.IntegerField(null=True)),
                ('isPrivate', models.BooleanField(default=False, null=True)),
                ('article_description', models.CharField(max_length=200, null=True)),
                ('reporter_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
            ],
        ),
    ]
