# Generated by Django 3.2 on 2023-08-14 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, null=True)),
                ('first_name', models.CharField(max_length=26)),
                ('last_name', models.CharField(max_length=26)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(blank=True, choices=[('ADMIN', 'ADMIN'), ('WRITER', 'WRITER'), ('REGISTERED', 'REGISTERED'), ('GUEST', 'GUEST')], max_length=10)),
                ('phone', models.CharField(default='444-444-4444', max_length=12)),
                ('bio', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('occupation', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('headline', models.CharField(max_length=100)),
                ('sub_title', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.IntegerField(null=True)),
                ('isPrivate', models.BooleanField(default=False, null=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('FOLLOWER/SUBSCRIBER ONLY', 'FOLLOWER/SUBSCRIBER ONLY'), ('PRIVATE', 'PRIVATE')], default=False, max_length=24, null=True)),
                ('article_description', models.CharField(max_length=500, null=True)),
                ('article_body', models.TextField(max_length=10000, null=True)),
                ('tags', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Science', 'Science'), ('Technology', 'Technology'), ('Work', 'Work'), ('School', 'School'), ('Life', 'Life'), ('Space', 'Space'), ('Outdoors', 'Outdoors')], max_length=20000, null=True)),
                ('article_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('reporter_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
            ],
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='api.account')),
                ('following_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='api.account')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=0)),
                ('commented_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.article')),
                ('commenter_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.comment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookmarkedArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
                ('saved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.article')),
            ],
        ),
    ]
