# Generated by Django 3.2.6 on 2022-03-11 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='reporter_account',
            new_name='account',
        ),
    ]
