# Generated by Django 3.2.6 on 2022-03-11 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_reporter_account_article_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='account',
            new_name='reporter_account',
        ),
    ]
