# Generated by Django 3.2 on 2023-08-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_commentvote_vote_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentvote',
            name='has_vote',
            field=models.BooleanField(default=False),
        ),
    ]
