# Generated by Django 3.2 on 2024-03-04 23:02

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_commentvote_has_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Science', 'Science'), ('Technology', 'Technology'), ('Work', 'Work'), ('School', 'School'), ('Life', 'Life'), ('Space', 'Space'), ('Outdoors', 'Outdoors'), ('Health', 'Health'), ('Food', 'Food'), ('Travel', 'Travel'), ('Fashion', 'Fashion'), ('Art', 'Art'), ('Music', 'Music'), ('Sports', 'Sports'), ('Entertainment', 'Entertainment'), ('History', 'History'), ('Politics', 'Politics'), ('Environment', 'Environment'), ('Business', 'Business'), ('Gaming', 'Gaming'), ('Fitness', 'Fitness'), ('Movies', 'Movies'), ('Books', 'Books'), ('Photography', 'Photography'), ('Pets', 'Pets'), ('Nature', 'Nature'), ('Crafts', 'Crafts'), ('Cooking', 'Cooking'), ('Travel', 'Travel'), ('DIY', 'DIY'), ('Home', 'Home')], max_length=20000, null=True),
        ),
        migrations.CreateModel(
            name='ArticleRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_vote', models.BooleanField(default=False)),
                ('vote_type', models.CharField(default='neutral', max_length=12)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.article')),
            ],
        ),
    ]
