# Generated by Django 3.2 on 2022-08-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_account_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('FOLLOWER/SUBSCRIBER ONLY', 'FOLLOWER/SUBSCRIBER ONLY'), ('PRIVATE', 'PRIVATE')], default=False, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
