# Generated by Django 3.2 on 2022-08-22 20:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220819_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Science', 'Science'), ('Technology', 'Technology'), ('Work', 'Work'), ('School', 'School'), ('Life', 'Life'), ('Space', 'Space'), ('Outdoors', 'Outdoors')], max_length=20000, null=True),
        ),
    ]
