# Generated by Django 3.2 on 2022-08-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_article_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_body',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
