# Generated by Django 3.2 on 2022-08-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_article_article_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_body',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='sub_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
