# Generated by Django 3.2 on 2022-09-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220825_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='key',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
