# Generated by Django 3.2 on 2022-09-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_article_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='key',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
