# Generated by Django 3.2 on 2022-10-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_account_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
