# Generated by Django 3.2 on 2022-10-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_article_article_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sub_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
