# Generated by Django 3.2 on 2022-10-03 19:19

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_article_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Science', 'Science'), ('Technology', 'Technology'), ('Work', 'Work'), ('School', 'School'), ('Life', 'Life'), ('Space', 'Space'), ('Outdoors', 'Outdoors')], max_length=20000, null=True),
        ),
    ]
