# Generated by Django 3.2 on 2022-10-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_article_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='occupation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'ADMIN'), ('WRITER', 'WRITER'), ('REGISTERED', 'REGISTERED'), ('GUEST', 'GUEST')], max_length=10),
        ),
    ]
