# Generated by Django 3.2 on 2023-06-30 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20221010_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(default=0)),
                ('commented_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.article')),
                ('commenter_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.comment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
