export const GET_ARTICLES = 'GET_ARTICLES';
export const GET_ARTICLESSUCCESS = 'GET_ARTICLESSUCCESS';
export const GET_ARTICLESFAIL = 'GET_ARTICLESFAIL';

export const GET_AUTH_ACCOUNT = 'GET_AUTH_ACCOUNT';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';