export const GET_ARTICLES = 'GET_ARTICLES';
export const GET_ARTICLESSUCCESS = 'GET_ARTICLESSUCCESS';
export const GET_ARTICLESFAIL = 'GET_ARTICLESFAIL';

//Couldnt get working (Edit)
export const GET_AUTH_ACCOUNT = 'GET_AUTH_ACCOUNT';
export const GET_AUTH_EDIT = 'GET_AUTH_EDIT';

export const GET_SAVED_ARTICLES_START = 'GET_SAVED_ARTICLES_START';
export const GET_SAVED_ARTICLES_FAIL = 'GET_SAVED_ARTICLES_FAIL';
export const GET_SAVED_ARTICLES_SUCCESS = 'GET_SAVED_ARTICLES_SUCESS';
export const GET_SAVED_ARTICLES = 'GET_SAVED_ARTICLES';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';